### ISSUE TITLE
speed up container boot

### ISSUE THREAD

**Issue by tlwt** [tlwt/paperyard#27]
integrate git clone of paperyard into build process
run git update 

integrate composer.phar in build process => copy it only in case it is not linked during development.
etc.

**Comment by tlwt** [comment]
@jannik-kramer can you move the composer setup procedure into the docker build file and just move it to the required directory if not existent?

**Comment by jannik-kramer** [comment]
As composer is published under MIT we could place the executable directly in the container. This way we would have to upgrade it manually, but we are not running into any backwards compatibility issues as we can test a specific version. And well, no need to download it every time on build or even run.

**Comment by jannik-kramer** [comment]
Unfortunately the long boot time is caused by `composer update`, not the installation of composer itself (still nice to have it in the docker build tho). There is currently no "quick check for updates" available.
To keep track of added or removed dependencies. It has to be run on every boot, just like `git clone`. In development mode it should do this too. Otherwise one has to take a close look at every commit if dependencies are added and run it manually.
